#!/bin/bash

# Arguments:
# 1: DEVICE
# 2: RELEASETYPE
# 3: PROGRESS_FILE (Optional, defaults to /dev/null)

DEVICE="$1"
RELEASETYPE="$2"
PROGRESS_FILE="${3:-/dev/null}"

echo "Initializing Signing Environment..."
source build/envsetup.sh > /dev/null
lunch axion_${DEVICE}-bp4a-${RELEASETYPE} > /dev/null

KEYS_DIR="vendor/axion-priv/keys"

# Validation
if [ ! -d "$KEYS_DIR" ]; then
    echo "❌ Error: Keys directory not found at $KEYS_DIR"
    echo "Please ensure keys are synced via manifest to vendor/axion-priv/keys"
    exit 1
fi

echo "Starting Signing & Packaging process..."

# --- STEP 1: SIGNING ---
echo "100,1,Signing Target Files..." > "$PROGRESS_FILE"

VERSION_RAW=$(get_build_var AXION_VERSION)
VERSION_LOWER=$(echo "$VERSION_RAW" | tr '[:upper:]' '[:lower:]')
AXION_BUILD_NAME="AxionOS_${DEVICE}-${VERSION_LOWER}"

# Find the target files zip generated by 'mka target-files-package'
TARGET_FILES_DIR="$OUT/obj/PACKAGING/target_files_intermediates"

# Priority 1: Check for ZIP file directly (Standard output of mka target-files-package)
TARGET_FILES_ZIP="$(find $TARGET_FILES_DIR -maxdepth 1 -name "*.zip" | head -n 1)"

# Priority 2: Check for Directory and append .zip (Some build systems output a dir first)
if [ -z "$TARGET_FILES_ZIP" ]; then
    TARGET_FILES_DIR_NAME="$(find $TARGET_FILES_DIR -mindepth 1 -maxdepth 1 -type d -name "*-target_files-*" | head -n 1)"
    if [ -n "$TARGET_FILES_DIR_NAME" ]; then
        TARGET_FILES_ZIP="${TARGET_FILES_DIR_NAME}.zip"
    fi
fi

if [ -z "$TARGET_FILES_ZIP" ] || [ ! -f "$TARGET_FILES_ZIP" ]; then
    echo "❌ Error: Could not find target files zip in $TARGET_FILES_DIR"
    exit 1
fi

echo "Found Target Files: $TARGET_FILES_ZIP"

echo "Signing target files..."
sign_target_files_apks -o -d ${KEYS_DIR} \
    --extra_apks AdServicesApk.apk=$KEYS_DIR/releasekey \
    --extra_apks FederatedCompute.apk=$KEYS_DIR/releasekey \
    --extra_apks HalfSheetUX.apk=$KEYS_DIR/releasekey \
    --extra_apks HealthConnectBackupRestore.apk=$KEYS_DIR/releasekey \
    --extra_apks HealthConnectController.apk=$KEYS_DIR/releasekey \
    --extra_apks OsuLogin.apk=$KEYS_DIR/releasekey \
    --extra_apks SafetyCenterResources.apk=$KEYS_DIR/releasekey \
    --extra_apks ServiceConnectivityResources.apk=$KEYS_DIR/releasekey \
    --extra_apks ServiceUwbResources.apk=$KEYS_DIR/releasekey \
    --extra_apks ServiceWifiResources.apk=$KEYS_DIR/releasekey \
    --extra_apks WifiDialog.apk=$KEYS_DIR/releasekey \
    --extra_apks com.android.adbd.apex=$KEYS_DIR/com.android.adbd \
    --extra_apks com.android.adservices.apex=$KEYS_DIR/com.android.adservices \
    --extra_apks com.android.adservices.api.apex=$KEYS_DIR/com.android.adservices.api \
    --extra_apks com.android.appsearch.apex=$KEYS_DIR/com.android.appsearch \
    --extra_apks com.android.appsearch.apk.apex=$KEYS_DIR/com.android.appsearch.apk \
    --extra_apks com.android.art.apex=$KEYS_DIR/com.android.art \
    --extra_apks com.android.bluetooth.apex=$KEYS_DIR/com.android.bluetooth \
    --extra_apks com.android.bt.apex=$KEYS_DIR/com.android.bt \
    --extra_apks com.android.btservices.apex=$KEYS_DIR/com.android.btservices \
    --extra_apks com.android.cellbroadcast.apex=$KEYS_DIR/com.android.cellbroadcast \
    --extra_apks com.android.compos.apex=$KEYS_DIR/com.android.compos \
    --extra_apks com.android.configinfrastructure.apex=$KEYS_DIR/com.android.configinfrastructure \
    --extra_apks com.android.connectivity.resources.apex=$KEYS_DIR/com.android.connectivity.resources \
    --extra_apks com.android.conscrypt.apex=$KEYS_DIR/com.android.conscrypt \
    --extra_apks com.android.crashrecovery.apex=$KEYS_DIR/com.android.crashrecovery \
    --extra_apks com.android.devicelock.apex=$KEYS_DIR/com.android.devicelock \
    --extra_apks com.android.extservices.apex=$KEYS_DIR/com.android.extservices \
    --extra_apks com.android.graphics.pdf.apex=$KEYS_DIR/com.android.graphics.pdf \
    --extra_apks com.android.hardware.authsecret.apex=$KEYS_DIR/com.android.hardware.authsecret \
    --extra_apks com.android.hardware.biometrics.face.virtual.apex=$KEYS_DIR/com.android.hardware.biometrics.face.virtual \
    --extra_apks com.android.hardware.biometrics.fingerprint.virtual.apex=$KEYS_DIR/com.android.hardware.biometrics.fingerprint.virtual \
    --extra_apks com.android.hardware.boot.apex=$KEYS_DIR/com.android.hardware.boot \
    --extra_apks com.android.hardware.cas.apex=$KEYS_DIR/com.android.hardware.cas \
    --extra_apks com.android.hardware.contexthub.apex=$KEYS_DIR/com.android.hardware.contexthub \
    --extra_apks com.android.hardware.dumpstate.apex=$KEYS_DIR/com.android.hardware.dumpstate \
    --extra_apks com.android.hardware.gatekeeper.nonsecure.apex=$KEYS_DIR/com.android.hardware.gatekeeper.nonsecure \
    --extra_apks com.android.hardware.neuralnetworks.apex=$KEYS_DIR/com.android.hardware.neuralnetworks \
    --extra_apks com.android.hardware.power.apex=$KEYS_DIR/com.android.hardware.power \
    --extra_apks com.android.hardware.rebootescrow.apex=$KEYS_DIR/com.android.hardware.rebootescrow \
    --extra_apks com.android.hardware.thermal.apex=$KEYS_DIR/com.android.hardware.thermal \
    --extra_apks com.android.hardware.threadnetwork.apex=$KEYS_DIR/com.android.hardware.threadnetwork \
    --extra_apks com.android.hardware.uwb.apex=$KEYS_DIR/com.android.hardware.uwb \
    --extra_apks com.android.hardware.vibrator.apex=$KEYS_DIR/com.android.hardware.vibrator \
    --extra_apks com.android.hardware.wifi.apex=$KEYS_DIR/com.android.hardware.wifi \
    --extra_apks com.android.healthfitness.apex=$KEYS_DIR/com.android.healthfitness \
    --extra_apks com.android.hotspot2.osulogin.apex=$KEYS_DIR/com.android.hotspot2.osulogin \
    --extra_apks com.android.i18n.apex=$KEYS_DIR/com.android.i18n \
    --extra_apks com.android.ipsec.apex=$KEYS_DIR/com.android.ipsec \
    --extra_apks com.android.media.apex=$KEYS_DIR/com.android.media \
    --extra_apks com.android.media.swcodec.apex=$KEYS_DIR/com.android.media.swcodec \
    --extra_apks com.android.mediaprovider.apex=$KEYS_DIR/com.android.mediaprovider \
    --extra_apks com.android.nearby.halfsheet.apex=$KEYS_DIR/com.android.nearby.halfsheet \
    --extra_apks com.android.networkstack.tethering.apex=$KEYS_DIR/com.android.networkstack.tethering \
    --extra_apks com.android.neuralnetworks.apex=$KEYS_DIR/com.android.neuralnetworks \
    --extra_apks com.android.nfcservices.apex=$KEYS_DIR/com.android.nfcservices \
    --extra_apks com.android.ondevicepersonalization.apex=$KEYS_DIR/com.android.ondevicepersonalization \
    --extra_apks com.android.os.statsd.apex=$KEYS_DIR/com.android.os.statsd \
    --extra_apks com.android.permission.apex=$KEYS_DIR/com.android.permission \
    --extra_apks com.android.profiling.apex=$KEYS_DIR/com.android.profiling \
    --extra_apks com.android.resolv.apex=$KEYS_DIR/com.android.resolv \
    --extra_apks com.android.rkpd.apex=$KEYS_DIR/com.android.rkpd \
    --extra_apks com.android.runtime.apex=$KEYS_DIR/com.android.runtime \
    --extra_apks com.android.safetycenter.resources.apex=$KEYS_DIR/com.android.safetycenter.resources \
    --extra_apks com.android.scheduling.apex=$KEYS_DIR/com.android.scheduling \
    --extra_apks com.android.sdkext.apex=$KEYS_DIR/com.android.sdkext \
    --extra_apks com.android.support.apexer.apex=$KEYS_DIR/com.android.support.apexer \
    --extra_apks com.android.telephony.apex=$KEYS_DIR/com.android.telephony \
    --extra_apks com.android.telephonycore.apex=$KEYS_DIR/com.android.telephonycore \
    --extra_apks com.android.telephonymodules.apex=$KEYS_DIR/com.android.telephonymodules \
    --extra_apks com.android.tethering.apex=$KEYS_DIR/com.android.tethering \
    --extra_apks com.android.tzdata.apex=$KEYS_DIR/com.android.tzdata \
    --extra_apks com.android.uprobestats.apex=$KEYS_DIR/com.android.uprobestats \
    --extra_apks com.android.uwb.apex=$KEYS_DIR/com.android.uwb \
    --extra_apks com.android.uwb.resources.apex=$KEYS_DIR/com.android.uwb.resources \
    --extra_apks com.android.virt.apex=$KEYS_DIR/com.android.virt \
    --extra_apks com.android.vndk.current.apex=$KEYS_DIR/com.android.vndk.current \
    --extra_apks com.android.vndk.current.on_vendor.apex=$KEYS_DIR/com.android.vndk.current.on_vendor \
    --extra_apks com.android.wifi.apex=$KEYS_DIR/com.android.wifi \
    --extra_apks com.android.wifi.dialog.apex=$KEYS_DIR/com.android.wifi.dialog \
    --extra_apks com.android.wifi.resources.apex=$KEYS_DIR/com.android.wifi.resources \
    --extra_apks com.google.pixel.camera.hal.apex=$KEYS_DIR/com.google.pixel.camera.hal \
    --extra_apks com.google.pixel.vibrator.hal.apex=$KEYS_DIR/com.google.pixel.vibrator.hal \
    --extra_apks com.qorvo.uwb.apex=$KEYS_DIR/com.qorvo.uwb \
    --extra_apex_payload_key com.android.adbd.apex=$KEYS_DIR/com.android.adbd.pem \
    --extra_apex_payload_key com.android.adservices.apex=$KEYS_DIR/com.android.adservices.pem \
    --extra_apex_payload_key com.android.adservices.api.apex=$KEYS_DIR/com.android.adservices.api.pem \
    --extra_apex_payload_key com.android.appsearch.apex=$KEYS_DIR/com.android.appsearch.pem \
    --extra_apex_payload_key com.android.appsearch.apk.apex=$KEYS_DIR/com.android.appsearch.apk.pem \
    --extra_apex_payload_key com.android.art.apex=$KEYS_DIR/com.android.art.pem \
    --extra_apex_payload_key com.android.bluetooth.apex=$KEYS_DIR/com.android.bluetooth.pem \
    --extra_apex_payload_key com.android.bt.apex=$KEYS_DIR/com.android.bt.pem \
    --extra_apex_payload_key com.android.btservices.apex=$KEYS_DIR/com.android.btservices.pem \
    --extra_apex_payload_key com.android.cellbroadcast.apex=$KEYS_DIR/com.android.cellbroadcast.pem \
    --extra_apex_payload_key com.android.compos.apex=$KEYS_DIR/com.android.compos.pem \
    --extra_apex_payload_key com.android.configinfrastructure.apex=$KEYS_DIR/com.android.configinfrastructure.pem \
    --extra_apex_payload_key com.android.connectivity.resources.apex=$KEYS_DIR/com.android.connectivity.resources.pem \
    --extra_apex_payload_key com.android.conscrypt.apex=$KEYS_DIR/com.android.conscrypt.pem \
    --extra_apex_payload_key com.android.crashrecovery.apex=$KEYS_DIR/com.android.crashrecovery.pem \
    --extra_apex_payload_key com.android.devicelock.apex=$KEYS_DIR/com.android.devicelock.pem \
    --extra_apex_payload_key com.android.extservices.apex=$KEYS_DIR/com.android.extservices.pem \
    --extra_apex_payload_key com.android.graphics.pdf.apex=$KEYS_DIR/com.android.graphics.pdf.pem \
    --extra_apex_payload_key com.android.hardware.authsecret.apex=$KEYS_DIR/com.android.hardware.authsecret.pem \
    --extra_apex_payload_key com.android.hardware.biometrics.face.virtual.apex=$KEYS_DIR/com.android.hardware.biometrics.face.virtual.pem \
    --extra_apex_payload_key com.android.hardware.biometrics.fingerprint.virtual.apex=$KEYS_DIR/com.android.hardware.biometrics.fingerprint.virtual.pem \
    --extra_apex_payload_key com.android.hardware.boot.apex=$KEYS_DIR/com.android.hardware.boot.pem \
    --extra_apex_payload_key com.android.hardware.cas.apex=$KEYS_DIR/com.android.hardware.cas.pem \
    --extra_apex_payload_key com.android.hardware.contexthub.apex=$KEYS_DIR/com.android.hardware.contexthub.pem \
    --extra_apex_payload_key com.android.hardware.dumpstate.apex=$KEYS_DIR/com.android.hardware.dumpstate.pem \
    --extra_apex_payload_key com.android.hardware.gatekeeper.nonsecure.apex=$KEYS_DIR/com.android.hardware.gatekeeper.nonsecure.pem \
    --extra_apex_payload_key com.android.hardware.neuralnetworks.apex=$KEYS_DIR/com.android.hardware.neuralnetworks.pem \
    --extra_apex_payload_key com.android.hardware.power.apex=$KEYS_DIR/com.android.hardware.power.pem \
    --extra_apex_payload_key com.android.hardware.rebootescrow.apex=$KEYS_DIR/com.android.hardware.rebootescrow.pem \
    --extra_apex_payload_key com.android.hardware.thermal.apex=$KEYS_DIR/com.android.hardware.thermal.pem \
    --extra_apex_payload_key com.android.hardware.threadnetwork.apex=$KEYS_DIR/com.android.hardware.threadnetwork.pem \
    --extra_apex_payload_key com.android.hardware.uwb.apex=$KEYS_DIR/com.android.hardware.uwb.pem \
    --extra_apex_payload_key com.android.hardware.vibrator.apex=$KEYS_DIR/com.android.hardware.vibrator.pem \
    --extra_apex_payload_key com.android.hardware.wifi.apex=$KEYS_DIR/com.android.hardware.wifi.pem \
    --extra_apex_payload_key com.android.healthfitness.apex=$KEYS_DIR/com.android.healthfitness.pem \
    --extra_apex_payload_key com.android.hotspot2.osulogin.apex=$KEYS_DIR/com.android.hotspot2.osulogin.pem \
    --extra_apex_payload_key com.android.i18n.apex=$KEYS_DIR/com.android.i18n.pem \
    --extra_apex_payload_key com.android.ipsec.apex=$KEYS_DIR/com.android.ipsec.pem \
    --extra_apex_payload_key com.android.media.apex=$KEYS_DIR/com.android.media.pem \
    --extra_apex_payload_key com.android.media.swcodec.apex=$KEYS_DIR/com.android.media.swcodec.pem \
    --extra_apex_payload_key com.android.mediaprovider.apex=$KEYS_DIR/com.android.mediaprovider.pem \
    --extra_apex_payload_key com.android.nearby.halfsheet.apex=$KEYS_DIR/com.android.nearby.halfsheet.pem \
    --extra_apex_payload_key com.android.networkstack.tethering.apex=$KEYS_DIR/com.android.networkstack.tethering.pem \
    --extra_apex_payload_key com.android.neuralnetworks.apex=$KEYS_DIR/com.android.neuralnetworks.pem \
    --extra_apex_payload_key com.android.nfcservices.apex=$KEYS_DIR/com.android.nfcservices.pem \
    --extra_apex_payload_key com.android.ondevicepersonalization.apex=$KEYS_DIR/com.android.ondevicepersonalization.pem \
    --extra_apex_payload_key com.android.os.statsd.apex=$KEYS_DIR/com.android.os.statsd.pem \
    --extra_apex_payload_key com.android.permission.apex=$KEYS_DIR/com.android.permission.pem \
    --extra_apex_payload_key com.android.profiling.apex=$KEYS_DIR/com.android.profiling.pem \
    --extra_apex_payload_key com.android.resolv.apex=$KEYS_DIR/com.android.resolv.pem \
    --extra_apex_payload_key com.android.rkpd.apex=$KEYS_DIR/com.android.rkpd.pem \
    --extra_apex_payload_key com.android.runtime.apex=$KEYS_DIR/com.android.runtime.pem \
    --extra_apex_payload_key com.android.safetycenter.resources.apex=$KEYS_DIR/com.android.safetycenter.resources.pem \
    --extra_apex_payload_key com.android.scheduling.apex=$KEYS_DIR/com.android.scheduling.pem \
    --extra_apex_payload_key com.android.sdkext.apex=$KEYS_DIR/com.android.sdkext.pem \
    --extra_apex_payload_key com.android.support.apexer.apex=$KEYS_DIR/com.android.support.apexer.pem \
    --extra_apex_payload_key com.android.telephony.apex=$KEYS_DIR/com.android.telephony.pem \
    --extra_apex_payload_key com.android.telephonycore.apex=$KEYS_DIR/com.android.telephonycore.pem \
    --extra_apex_payload_key com.android.telephonymodules.apex=$KEYS_DIR/com.android.telephonymodules.pem \
    --extra_apex_payload_key com.android.tethering.apex=$KEYS_DIR/com.android.tethering.pem \
    --extra_apex_payload_key com.android.tzdata.apex=$KEYS_DIR/com.android.tzdata.pem \
    --extra_apex_payload_key com.android.uprobestats.apex=$KEYS_DIR/com.android.uprobestats.pem \
    --extra_apex_payload_key com.android.uwb.apex=$KEYS_DIR/com.android.uwb.pem \
    --extra_apex_payload_key com.android.uwb.resources.apex=$KEYS_DIR/com.android.uwb.resources.pem \
    --extra_apex_payload_key com.android.virt.apex=$KEYS_DIR/com.android.virt.pem \
    --extra_apex_payload_key com.android.vndk.current.apex=$KEYS_DIR/com.android.vndk.current.pem \
    --extra_apex_payload_key com.android.vndk.current.on_vendor.apex=$KEYS_DIR/com.android.vndk.current.on_vendor.pem \
    --extra_apex_payload_key com.android.wifi.apex=$KEYS_DIR/com.android.wifi.pem \
    --extra_apex_payload_key com.android.wifi.dialog.apex=$KEYS_DIR/com.android.wifi.dialog.pem \
    --extra_apex_payload_key com.android.wifi.resources.apex=$KEYS_DIR/com.android.wifi.resources.pem \
    --extra_apex_payload_key com.google.pixel.camera.hal.apex=$KEYS_DIR/com.google.pixel.camera.hal.pem \
    --extra_apex_payload_key com.google.pixel.vibrator.hal.apex=$KEYS_DIR/com.google.pixel.vibrator.hal.pem \
    --extra_apex_payload_key com.qorvo.uwb.apex=$KEYS_DIR/com.qorvo.uwb.pem \
    "$TARGET_FILES_ZIP" \
    "${OUT}/${AXION_BUILD_NAME}-signed-target_files.zip" || { echo "Signing Failed!"; exit 1; }

# --- STEP 2: PACKAGING ---
echo "100,1,Generating OTA Zip..." > "$PROGRESS_FILE"

echo "Generating installable OTA zip..."
ota_from_target_files -k ${KEYS_DIR}/releasekey \
    --block --backup=true \
    "${OUT}/${AXION_BUILD_NAME}-signed-target_files.zip" \
    "${OUT}/${AXION_BUILD_NAME}.zip" || { echo "Packaging Failed!"; exit 1; }

# Cleanup Signed Target Files to save space
echo "Cleaning up signed target files..."
rm -f "${OUT}/${AXION_BUILD_NAME}-signed-target_files.zip"

echo "Signing & Packaging Complete."